version: '3.1'

services:
  nginx:
    image: nginx:1.14.2-alpine
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./data-volumns/wordpress:/var/www/html
    links:
      - wordpress
    restart: always

  wordpress:
    image: wordpress:php7.2-fpm-alpine
    restart: always
    volumes:
      - ./data-volumns/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb

  db:
    image: mariadb:10.3.11-bionic
    restart: always
    volumes:
      - ./conf/mysql:/etc/mysql/conf.d
      - ./data-volumns/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
